database:
  dbname: "DBNAME"
  user: "USER"
  password: "PASSWORD"
  host: "HOST"
  port: "PORT"

database_emb:
  dbname: "DBNAME"
  user: "USER"
  password: "PASSWORD"
  host: "HOST"
  port: "PORT"

model:
  bert_pretrained: "distilbert-base-uncased"
  mha_embed_dim: 64
  mha_heads: 4
  final_dim: 32
  genre_embed_dim: 32
  margin: 0.2

training:
  num_epochs: 3
  learning_rate: 1e-4
  batch_size: 32
  save_path: "song_genre_model.pt"