database:
  dbname: "postgres"
  user: "postgres"
  password: "1234"
  host: "34.64.81.75"
  port: "5432"

database_emb:
  dbname: "embedding"
  user: "postgres"
  password: "1234"
  host: "34.64.81.75"
  port: "5432"

model:
  bert_pretrained: "distilbert-base-uncased"
  mha_embed_dim: 64
  mha_heads: 4
  final_dim: 32
  genre_embed_dim: 32
  margin: 0.2

training:
  num_epochs: 3
  learning_rate: 1e-4
  batch_size: 16
  save_path: "song_genre_model.pt"