version: 1
formatters:
  default:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    class: logging.Formatter
  timezone_formatter:
    "()": app.config.formatter.TimezoneFormatter  # 커스텀 포맷터 설정
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: timezone_formatter
    filename: uvicorn.log

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: timezone_formatter

loggers:
  uvicorn:
    level: INFO
    handlers: [file, console]
    propagate: False

  uvicorn.access:
    level: INFO
    handlers: [file, console]
    propagate: False

root:
  level: INFO
  handlers: [file, console]
